# Interactive first-run setup. Empty answers keep the defaults:
#   admin / admin, SMTP 1025, dashboard 8025
$ErrorActionPreference = "Stop"
Set-Location -LiteralPath $PSScriptRoot

function Read-Default([string]$Name, [string]$Default) {
    $value = Read-Host "$Name [$Default]"
    if ([string]::IsNullOrWhiteSpace($value)) { return $Default }
    return $value
}

function Test-Port([string]$Value) {
    $n = 0
    return [int]::TryParse($Value, [ref]$n) -and $n -ge 1 -and $n -le 65535
}

function Yaml-Quote([string]$Value) {
    return "'" + ($Value -replace "'", "''") + "'"
}

Write-Host "smtp-relay setup"
Write-Host "Press Enter to keep each default."
Write-Host ""

$adminUser = Read-Default "Admin username" "admin"
$adminPass = Read-Default "Admin password" "admin"
$smtpPort = Read-Default "Inbound SMTP port" "1025"
$webPort = Read-Default "Dashboard / web port" "8025"

if ([string]::IsNullOrWhiteSpace($adminUser)) {
    throw "admin username must not be empty"
}
if (-not (Test-Port $smtpPort)) {
    throw "SMTP port must be 1-65535 (got $smtpPort)"
}
if (-not (Test-Port $webPort)) {
    throw "web port must be 1-65535 (got $webPort)"
}

$out = Join-Path $PSScriptRoot "config.yaml"
if (Test-Path -LiteralPath $out) {
    $ans = Read-Host "$out already exists. Overwrite? [y/N]"
    if ($ans -notmatch '^[yY](es)?$') {
        Write-Host "Aborted; existing config left unchanged."
        exit 1
    }
}

@"
# Generated by setup.ps1. See config.example.yaml for every option.
# Add upstream SMTP providers from the dashboard after start.

server:
  bind_address: "0.0.0.0:${smtpPort}"
  hostname: "smtp-proxy.local"

admin:
  enabled: true
  bind_address: "0.0.0.0:${webPort}"
  username: $(Yaml-Quote $adminUser)
  password: $(Yaml-Quote $adminPass)
  dashboard_enabled: true
  allow_config_write: true

relays: []
"@ | Set-Content -LiteralPath $out -Encoding utf8

Write-Host ""
Write-Host "Wrote $out"
Write-Host "  SMTP listener : 0.0.0.0:${smtpPort}"
Write-Host "  Dashboard     : http://127.0.0.1:${webPort}/  (user $adminUser)"
Write-Host ""
Write-Host "Build and start:"
Write-Host "  cargo build --release"
Write-Host "  .\target\release\smtp-relay.exe"
Write-Host ""
Write-Host "Then open the dashboard and add SMTP providers."
Write-Host "New providers default to port 465 / SSL. From matches the username"
Write-Host "unless you uncheck that option. MAIL FROM alignment (SPF) is off."
