#!/usr/bin/env bash
# Interactive first-run setup. Empty answers keep the defaults:
#   admin / admin, SMTP 1025, dashboard 8025
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

DEFAULT_USER="admin"
DEFAULT_PASS="admin"
DEFAULT_SMTP="1025"
DEFAULT_WEB="8025"

prompt() {
  local name="$1"
  local default="$2"
  local value=""
  read -r -p "${name} [${default}]: " value || true
  if [ -z "${value}" ]; then
    printf '%s' "$default"
  else
    printf '%s' "$value"
  fi
}

yaml_quote() {
  local s=$1
  s=${s//\'/\'\'}
  printf "'%s'" "$s"
}

is_port() {
  case "$1" in
    ''|*[!0-9]*) return 1 ;;
  esac
  [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

echo "smtp-relay setup"
echo "Press Enter to keep each default."
echo

ADMIN_USER="$(prompt "Admin username" "$DEFAULT_USER")"
ADMIN_PASS="$(prompt "Admin password" "$DEFAULT_PASS")"
SMTP_PORT="$(prompt "Inbound SMTP port" "$DEFAULT_SMTP")"
WEB_PORT="$(prompt "Dashboard / web port" "$DEFAULT_WEB")"

if [ -z "$ADMIN_USER" ]; then
  echo "admin username must not be empty" >&2
  exit 1
fi
if ! is_port "$SMTP_PORT"; then
  echo "SMTP port must be 1-65535 (got ${SMTP_PORT})" >&2
  exit 1
fi
if ! is_port "$WEB_PORT"; then
  echo "web port must be 1-65535 (got ${WEB_PORT})" >&2
  exit 1
fi

OUT="$ROOT/config.yaml"
WRITE_CONFIG=1
if [ -f "$OUT" ]; then
  ans=""
  read -r -p "${OUT} already exists. Overwrite? [y/N]: " ans || true
  case "$ans" in
    y|Y|yes|YES) WRITE_CONFIG=1 ;;
    *)
      WRITE_CONFIG=0
      echo "Keeping existing ${OUT}"
      ;;
  esac
fi

if [ "$WRITE_CONFIG" -eq 1 ]; then
  cat > "$OUT" <<EOF
# Generated by setup.sh. See config.example.yaml for every option.
# Add upstream SMTP providers from the dashboard after start.
# Change admin.password / server.auth_users later if you want.

server:
  bind_address: "0.0.0.0:${SMTP_PORT}"
  hostname: "smtp-proxy.local"
  require_auth: true
  auth_users:
    - username: $(yaml_quote "$ADMIN_USER")
      password: $(yaml_quote "$ADMIN_PASS")

admin:
  enabled: true
  bind_address: "0.0.0.0:${WEB_PORT}"
  username: $(yaml_quote "$ADMIN_USER")
  password: $(yaml_quote "$ADMIN_PASS")
  dashboard_enabled: true
  allow_config_write: true

queue:
  persist: true
  directory: "/var/lib/smtp-relay/spool"

relays: []
EOF
  echo
  echo "Wrote ${OUT}"
  echo "  SMTP listener : 0.0.0.0:${SMTP_PORT}"
  echo "  SMTP AUTH     : ${ADMIN_USER}  (same password as dashboard; edit config.yaml to change)"
  echo "  Dashboard     : http://0.0.0.0:${WEB_PORT}/  (user ${ADMIN_USER})"
fi

if [ -f "$HOME/.cargo/env" ]; then
  # shellcheck disable=SC1091
  . "$HOME/.cargo/env"
fi

if command -v cargo >/dev/null 2>&1; then
  echo
  echo "Building release binary…"
  cargo build --release
else
  echo
  echo "cargo not found; install Rust or build later."
fi

BIN="$ROOT/target/release/smtp-relay"
if [ ! -x "$BIN" ]; then
  echo
  echo "No binary at ${BIN}. Service was not installed."
  echo "After cargo build --release, run ./setup.sh again."
  exit 0
fi

if ! command -v systemctl >/dev/null 2>&1 || [ ! -d /run/systemd/system ]; then
  echo
  echo "systemd not available. Start with:"
  echo "  ${BIN}"
  exit 0
fi

if [ "$(id -u)" -eq 0 ]; then
  SUDO=""
else
  if command -v sudo >/dev/null 2>&1; then
    SUDO="sudo"
  else
    echo "Need root to install the systemd service (no sudo)."
    echo "Start with: ${BIN}"
    exit 0
  fi
fi

echo
echo "Installing systemd service…"
$SUDO install -m 0755 "$BIN" /usr/local/bin/smtp-relay
$SUDO mkdir -p /etc/smtp-relay /var/lib/smtp-relay/spool
$SUDO cp "$OUT" /etc/smtp-relay/config.yaml
$SUDO chmod 640 /etc/smtp-relay/config.yaml

$SUDO tee /etc/systemd/system/smtp-relay.service >/dev/null <<'UNIT'
[Unit]
Description=SMTP proxy and load-balancing relay
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/smtp-relay --config /etc/smtp-relay/config.yaml
WorkingDirectory=/var/lib/smtp-relay
Restart=on-failure
RestartSec=2s
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
UNIT

$SUDO systemctl daemon-reload
$SUDO systemctl enable smtp-relay
if $SUDO systemctl restart smtp-relay; then
  $SUDO systemctl --no-pager --full status smtp-relay || true
  echo
  echo "smtp-relay is installed and running as a systemd service."
  echo "  sudo systemctl status smtp-relay"
  echo "  sudo systemctl restart smtp-relay"
  echo "  sudo journalctl -u smtp-relay -f"
  echo
  echo "Dashboard: http://$(hostname -I 2>/dev/null | awk '{print $1}'):${WEB_PORT}/"
  echo "SMTP AUTH : ${ADMIN_USER}  port ${SMTP_PORT}"
else
  echo
  echo "Service installed but failed to start. If a foreground smtp-relay is still"
  echo "running, stop it (Ctrl+C) and run: sudo systemctl restart smtp-relay"
  echo "Logs: sudo journalctl -u smtp-relay -e"
fi
