#!/usr/bin/env bash
# Interactive first-run setup. Empty answers keep the defaults:
#   admin / admin, SMTP 1025, dashboard 8025
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

DEFAULT_USER="admin"
DEFAULT_PASS="admin"
DEFAULT_SMTP="1025"
DEFAULT_WEB="8025"

prompt() {
  local name="$1"
  local default="$2"
  local value=""
  read -r -p "${name} [${default}]: " value || true
  if [ -z "${value}" ]; then
    printf '%s' "$default"
  else
    printf '%s' "$value"
  fi
}

yaml_quote() {
  local s=$1
  s=${s//\'/\'\'}
  printf "'%s'" "$s"
}

is_port() {
  case "$1" in
    ''|*[!0-9]*) return 1 ;;
  esac
  [ "$1" -ge 1 ] && [ "$1" -le 65535 ]
}

echo "smtp-relay setup"
echo "Press Enter to keep each default."
echo

ADMIN_USER="$(prompt "Admin username" "$DEFAULT_USER")"
ADMIN_PASS="$(prompt "Admin password" "$DEFAULT_PASS")"
SMTP_PORT="$(prompt "Inbound SMTP port" "$DEFAULT_SMTP")"
WEB_PORT="$(prompt "Dashboard / web port" "$DEFAULT_WEB")"

if [ -z "$ADMIN_USER" ]; then
  echo "admin username must not be empty" >&2
  exit 1
fi
if ! is_port "$SMTP_PORT"; then
  echo "SMTP port must be 1-65535 (got ${SMTP_PORT})" >&2
  exit 1
fi
if ! is_port "$WEB_PORT"; then
  echo "web port must be 1-65535 (got ${WEB_PORT})" >&2
  exit 1
fi

OUT="$ROOT/config.yaml"
if [ -f "$OUT" ]; then
  ans=""
  read -r -p "${OUT} already exists. Overwrite? [y/N]: " ans || true
  case "$ans" in
    y|Y|yes|YES) ;;
    *)
      echo "Aborted; existing config left unchanged."
      exit 1
      ;;
  esac
fi

cat > "$OUT" <<EOF
# Generated by setup.sh. See config.example.yaml for every option.
# Add upstream SMTP providers from the dashboard after start.
# Change admin.password / server.auth_users later if you want.

server:
  bind_address: "0.0.0.0:${SMTP_PORT}"
  hostname: "smtp-proxy.local"
  require_auth: true
  auth_users:
    - username: $(yaml_quote "$ADMIN_USER")
      password: $(yaml_quote "$ADMIN_PASS")

admin:
  enabled: true
  bind_address: "0.0.0.0:${WEB_PORT}"
  username: $(yaml_quote "$ADMIN_USER")
  password: $(yaml_quote "$ADMIN_PASS")
  dashboard_enabled: true
  allow_config_write: true

relays: []
EOF

echo
echo "Wrote ${OUT}"
echo "  SMTP listener : 0.0.0.0:${SMTP_PORT}"
echo "  SMTP AUTH     : ${ADMIN_USER}  (same password as dashboard; edit config.yaml to change)"
echo "  Dashboard     : http://127.0.0.1:${WEB_PORT}/  (user ${ADMIN_USER})"
echo
echo "Build and start:"
echo "  cargo build --release"
echo "  ./target/release/smtp-relay"
echo
echo "Then open the dashboard and add SMTP providers."
echo "New providers default to port 465 / SSL. From matches the username"
echo "unless you uncheck that option. MAIL FROM alignment (SPF) is off."
